services:

  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cash_flow
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
